### PR TITLE
Small improvements

### PR DESCRIPTION
**Pull request by smitdylan2001**
Made some small improvements to the setup
- Changes settings for faster builds, better performance and faster loadtimes
- Simplified graphics tiers, since most go unused

### CODE REVIEW

**Review by LoakSubmissions — CHANGES_REQUESTED** [review]
First off, thank you so much for the contributions! We really appreciate it.

Most of these changes are good and I definitely want them in the project, but there's a few that I'd like you to revert before I can approve this PR. Keep in mind that, especially with project settings, our bias is towards keeping as many settings default as possible to prevent confusion for less experienced developers.

1. m_VideoShadersIncludeMode ("Video" setting in Graphics settings) - This setting is great to have in a project that you have total control of, but in the event that it doesn't properly detect the use of the shader, it could really confuse someone who doesn't realize it's not set to the default setting.

2. androidUseSwappy (Optimized Frame Pacing) - This option is defaulted on for good reason. In almost any situation, it has desirable results. In fact, in a limited, unscientific test on the Loak client, it actually seemed to degrade the experience when turned off.

3. bakeCollisionMeshes - This setting is very dependent on what kind of experience a dev is creating, especially on mobile platforms. Best to keep it default and let the individual dev decide.

4. m_DynamicBatching - Similar situation to baking collision meshes. It can have great performance benefits in some scenarios, but can hurt others. Best to leave default.

5. The Quality Settings changes you made in your second commit are too numerous and drastic for me to accurately test and validate with the limited time that I have. If you have any specific recommendations from them, I'm all ears, but for now these should remain default.

Sorry for the long review, just wanted to make sure you understood the reason for my decisions. If you revert the settings mentioned above, I'll happily approve this PR. If any of these settings I've asked you to revert are definitely 100% beneficial for AR experiences, please provide me with a source for this so that I may investigate.

**Comment by smitdylan2001** [comment]
Thanks for the feedback. While I agree with some, I don't agree with others for the following reasons.

3. What would the downside of this be? Any referenced mesh colliders will be prebaked. If you use anything procedural, or if something does not prebake, it will use the regular routine.
4. Dynamic batching really should be enabled for AR experiences. It is on for some unity versions, idk why it's off for this one. Static batching does not work well in AR since models almost never are static. Dynamic batching enabled does not have any downsides as far as I know. 
5. Having 5 quality tiers is really useless, and since they all were enabled they all are being compiled in every build. Increasing build size and build duration. I simply kept the quality tiers mobile and desktop used, so this does not change anything

**Comment by LoakSubmissions** [comment]
> 3. What would the downside of this be? Any referenced mesh colliders will be prebaked. If you use anything procedural, or if something does not prebake, it will use the regular routine.

Prebaking is a tradeoff between performance and disk/memory size. It also often has negligible or no benefits for simpler experiences. The main time it has a benefit is when using a high poly mesh as a collider, which is bad practice anyway. As I mentioned in my previous comment, we'd like to keep things default for simplicity's sake unless it's basically always a benefit.

> 4. Dynamic batching really should be enabled for AR experiences. It is on for some unity versions, idk why it's off for this one. Static batching does not work well in AR since models almost never are static. Dynamic batching enabled does not have any downsides as far as I know.

After looking into this one a bit more, it does seem to be defaulted on in newer versions (and even hidden in some cases). Knowing this, I'm actually fine with changing it. You can keep this change.

> 5. Having 5 quality tiers is really useless, and since they all were enabled they all are being compiled in every build. Increasing build size and build duration. I simply kept the quality tiers mobile and desktop used, so this does not change anything

I didn't have the time to properly look into this one last time, but I do see now that you just removed the unused presets. This is fine to keep.

Sorry it took me so long to get back to this. Thank you for providing more clarification and challenging me on these points. I really appreciate your contribution. If you make those changes I've requested, we can get this merged in nice and quick!

**Comment by smitdylan2001** [comment]
Awesome, made the changes!
Maybe also make sure the app name by default is not DefaultCompany.
And maybe disable the splash screen so those with unity pro are not plagued by it ;)

**Comment by LoakSubmissions** [comment]
Thank you @smitdylan2001! Love to see improvements from the community 🚀

**Pull request merged**
